<?php
/**
 * Acıbadem International Offices — Installation Wizard
 * This file sets up the database and configuration.
 * DELETE THIS FILE after successful installation!
 */
session_start();

// Check if already installed
if (file_exists(__DIR__ . '/config.php')) {
    require_once __DIR__ . '/config.php';
    if (defined('APP_INSTALLED') && APP_INSTALLED) {
        header('Location: index.php');
        exit;
    }
}

$step = 'form'; // form, processing, success, error
$errors = [];
$success = false;

// CSRF token
if (empty($_SESSION['csrf_token'])) {
    $_SESSION['csrf_token'] = bin2hex(random_bytes(32));
}

$countOffices = 0;
$countCountries = 0;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Verify CSRF
    if (!hash_equals($_SESSION['csrf_token'], $_POST['csrf_token'] ?? '')) {
        $errors[] = 'Invalid security token. Please try again.';
    } else {
        $dbHost = trim($_POST['db_host'] ?? 'localhost');
        $dbPort = trim($_POST['db_port'] ?? '3306');
        $dbName = trim($_POST['db_name'] ?? 'asg_offices');
        $dbUser = trim($_POST['db_user'] ?? '');
        $dbPass = $_POST['db_pass'] ?? '';
        $appUrl = rtrim(trim($_POST['app_url'] ?? ''), '/');
        
        // Validate
        if (empty($dbName)) $errors[] = 'Database name is required.';
        if (empty($dbUser)) $errors[] = 'Database username is required.';
        
        if (empty($errors)) {
            try {
                // Test connection
                $dsn = "mysql:host={$dbHost};port={$dbPort};charset=utf8mb4";
                $pdo = new PDO($dsn, $dbUser, $dbPass, [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
                ]);
                
                // Create database if not exists
                $pdo->exec("CREATE DATABASE IF NOT EXISTS `" . str_replace('`', '``', $dbName) . "` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
                $pdo->exec("USE `" . str_replace('`', '``', $dbName) . "`");
                
                // Run schema
                $schemaFile = __DIR__ . '/database/schema.sql';
                if (file_exists($schemaFile)) {
                    $schema = file_get_contents($schemaFile);
                    if ($schema) {
                        $pdo->exec($schema);
                    }
                } else {
                    $errors[] = "Schema file not found at $schemaFile";
                }
                
                // Run seed data
                $seedFile = __DIR__ . '/database/seed.sql';
                if (file_exists($seedFile)) {
                    $seed = file_get_contents($seedFile);
                    if ($seed) {
                        // Split by semicolons and execute each statement
                        $statements = array_filter(array_map('trim', explode(';', $seed)));
                        foreach ($statements as $stmt) {
                            if (!empty($stmt) && stripos($stmt, 'INSERT') !== false) {
                                $pdo->exec($stmt);
                            } elseif (!empty($stmt) && stripos($stmt, 'SET') !== false) {
                                $pdo->exec($stmt);
                            }
                        }
                    }
                } else {
                    $errors[] = "Seed file not found at $seedFile";
                }
                
                if (empty($errors)) {
                    // Try to get counts
                    try {
                        $countOffices = $pdo->query("SELECT count(*) FROM offices")->fetchColumn();
                        $countCountries = $pdo->query("SELECT count(DISTINCT country) FROM offices")->fetchColumn();
                    } catch (Exception $e) {
                        // Ignore
                    }
                    
                    // Generate config.php
                    $appSecret = bin2hex(random_bytes(32));
                    $configContent = "<?php\n";
                    $configContent .= "// Auto-generated by installer on " . date('Y-m-d H:i:s') . "\n";
                    $configContent .= "// WARNING: This file contains sensitive credentials. Keep it secure!\n\n";
                    $configContent .= "define('DB_HOST', " . var_export($dbHost, true) . ");\n";
                    $configContent .= "define('DB_PORT', " . var_export($dbPort, true) . ");\n";
                    $configContent .= "define('DB_NAME', " . var_export($dbName, true) . ");\n";
                    $configContent .= "define('DB_USER', " . var_export($dbUser, true) . ");\n";
                    $configContent .= "define('DB_PASS', " . var_export($dbPass, true) . ");\n";
                    $configContent .= "define('APP_SECRET', " . var_export($appSecret, true) . ");\n";
                    $configContent .= "define('APP_URL', " . var_export($appUrl, true) . ");\n";
                    $configContent .= "define('APP_INSTALLED', true);\n";
                    
                    if (file_put_contents(__DIR__ . '/config.php', $configContent) === false) {
                        $errors[] = 'Could not write config.php. Please check file permissions on the root directory.';
                    } else {
                        $success = true;
                        $step = 'success';
                    }
                }
            } catch (PDOException $e) {
                $errors[] = 'Database error: ' . $e->getMessage();
            }
        }
    }
    
    if (!empty($errors)) {
        $step = 'error';
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Installation — Acıbadem International Offices</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <script src="https://unpkg.com/@phosphor-icons/web"></script>
    <link rel="icon" type="image/png" href="assets/images/favicon.png">
    <link rel="icon" type="image/x-icon" href="assets/images/favicon.ico">
    <style>
        body { font-family: 'Plus Jakarta Sans', sans-serif; background-color: #f8fafc; }
    </style>
</head>
<body>

    <!-- Header -->
    <header class="bg-[#0c2d74] text-white py-4 shadow-md">
        <div class="max-w-3xl mx-auto px-4 flex items-center justify-between">
            <div class="flex items-center gap-3">
                <img class="h-8 w-auto" src="assets/images/acibadem-white-logo.webp" alt="Acıbadem Logo">
            </div>
            <div class="text-xs uppercase tracking-widest text-blue-200 font-semibold bg-white/10 px-3 py-1.5 rounded-full border border-white/10">
                Installation Wizard
            </div>
        </div>
    </header>

    <div class="max-w-3xl mx-auto px-4 py-12">
        <div class="bg-white rounded-3xl shadow-xl border border-gray-100 overflow-hidden">
            <div class="p-8 md:p-10">
                <h1 class="text-3xl font-bold text-[#0A1C36] mb-2">Installation Wizard</h1>
                <p class="text-gray-500 mb-8">Set up your database connection and basic configuration.</p>

                <?php if ($step === 'error'): ?>
                    <div class="bg-red-50 border-l-4 border-red-500 p-4 mb-8 rounded-r-lg">
                        <div class="flex items-start">
                            <i class="ph-fill ph-warning-circle text-red-500 text-xl mt-0.5 mr-3"></i>
                            <div>
                                <h3 class="text-red-800 font-bold mb-1">Installation Failed</h3>
                                <ul class="text-red-700 text-sm list-disc pl-4 space-y-1">
                                    <?php foreach ($errors as $err): ?>
                                        <li><?= htmlspecialchars($err) ?></li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>

                <?php if ($step === 'success'): ?>
                    <div class="text-center py-6">
                        <div class="w-20 h-20 bg-green-100 text-green-600 rounded-full flex items-center justify-center mx-auto mb-6">
                            <i class="ph-fill ph-check-circle text-5xl"></i>
                        </div>
                        <h2 class="text-3xl font-bold text-gray-900 mb-4">Installation Complete!</h2>
                        <p class="text-lg text-gray-600 mb-8">Your database has been set up with <?= $countOffices ?> offices across <?= $countCountries ?> countries.</p>
                        
                        <div class="bg-amber-50 border border-amber-200 p-6 rounded-2xl mb-8">
                            <div class="flex items-start gap-4 text-left">
                                <i class="ph-fill ph-warning text-amber-500 text-3xl"></i>
                                <div>
                                    <h3 class="font-bold text-amber-900 mb-1">Security Warning</h3>
                                    <p class="text-amber-800 text-sm">For security reasons, please DELETE the <strong>install.php</strong> file from your server immediately!</p>
                                </div>
                            </div>
                        </div>

                        <a href="/" class="inline-block bg-[#0c2d74] text-white hover:bg-[#1a4ba0] font-semibold py-4 px-10 rounded-xl transition-colors text-lg shadow-md">
                            Go to Homepage
                        </a>
                    </div>
                <?php else: ?>
                    <form method="POST" action="install.php" class="space-y-6">
                        <input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['csrf_token']) ?>">
                        
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                            <div>
                                <label class="block text-sm font-semibold text-gray-700 mb-2">Database Host</label>
                                <input type="text" name="db_host" value="<?= htmlspecialchars($_POST['db_host'] ?? 'localhost') ?>" class="w-full px-4 py-3 rounded-xl border border-gray-300 focus:border-[#0c2d74] focus:ring-1 focus:ring-[#0c2d74] outline-none">
                            </div>
                            <div>
                                <label class="block text-sm font-semibold text-gray-700 mb-2">Database Port</label>
                                <input type="text" name="db_port" value="<?= htmlspecialchars($_POST['db_port'] ?? '3306') ?>" class="w-full px-4 py-3 rounded-xl border border-gray-300 focus:border-[#0c2d74] focus:ring-1 focus:ring-[#0c2d74] outline-none">
                            </div>
                        </div>

                        <div>
                            <label class="block text-sm font-semibold text-gray-700 mb-2">Database Name <span class="text-red-500">*</span></label>
                            <input type="text" name="db_name" value="<?= htmlspecialchars($_POST['db_name'] ?? 'asg_offices') ?>" required class="w-full px-4 py-3 rounded-xl border border-gray-300 focus:border-[#0c2d74] focus:ring-1 focus:ring-[#0c2d74] outline-none">
                            <p class="text-xs text-gray-500 mt-1">The database will be created if it doesn't exist (requires sufficient privileges).</p>
                        </div>

                        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                            <div>
                                <label class="block text-sm font-semibold text-gray-700 mb-2">Database Username <span class="text-red-500">*</span></label>
                                <input type="text" name="db_user" value="<?= htmlspecialchars($_POST['db_user'] ?? '') ?>" required class="w-full px-4 py-3 rounded-xl border border-gray-300 focus:border-[#0c2d74] focus:ring-1 focus:ring-[#0c2d74] outline-none">
                            </div>
                            <div>
                                <label class="block text-sm font-semibold text-gray-700 mb-2">Database Password</label>
                                <input type="password" name="db_pass" class="w-full px-4 py-3 rounded-xl border border-gray-300 focus:border-[#0c2d74] focus:ring-1 focus:ring-[#0c2d74] outline-none">
                            </div>
                        </div>

                        <div class="pt-4 border-t border-gray-100">
                            <label class="block text-sm font-semibold text-gray-700 mb-2">App URL (Optional)</label>
                            <input type="url" name="app_url" value="<?= htmlspecialchars($_POST['app_url'] ?? '') ?>" placeholder="e.g. https://offices.acibadem.com" class="w-full px-4 py-3 rounded-xl border border-gray-300 focus:border-[#0c2d74] focus:ring-1 focus:ring-[#0c2d74] outline-none">
                            <p class="text-xs text-gray-500 mt-1">Leave empty to auto-detect based on the current request.</p>
                        </div>

                        <div class="pt-6">
                            <button type="submit" class="w-full bg-[#0c2d74] text-white hover:bg-[#1a4ba0] font-semibold py-4 px-6 rounded-xl transition-colors shadow-md flex justify-center items-center gap-2">
                                <i class="ph-fill ph-database text-xl"></i>
                                Install App
                            </button>
                        </div>
                    </form>
                <?php endif; ?>
            </div>
        </div>
    </div>

</body>
</html>
