/**
 * Builds a small self-hosted Phosphor icon set for the public site (new design).
 * Scans the public PHP/JS files for "ph-<name>" classes and writes only those glyphs:
 *   assets/fonts/phosphor-regular.woff2, assets/fonts/phosphor-fill.woff2, assets/css/icons.css
 * Run `npm run build:icons` after using a new icon (the CDN script loads ~6 icon weights instead).
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, extname } from 'node:path';
import subsetFont from 'subset-font';
import { createHash } from 'node:crypto';

const root = new URL('..', import.meta.url).pathname;
const pkg = join(root, 'node_modules/@phosphor-icons/web/src');
const scan = ['.', 'includes', 'assets/js'];

function files(dir, deep) {
  return readdirSync(join(root, dir)).flatMap((f) => {
    const rel = join(dir, f);
    if (statSync(join(root, rel)).isDirectory()) return deep && !/node_modules|admin|\.git/.test(rel) ? files(rel, true) : [];
    return ['.php', '.js'].includes(extname(f)) ? [rel] : [];
  });
}
const sources = scan.flatMap((d) => files(d, d !== '.'));
const used = new Set();
for (const f of sources) for (const m of readFileSync(join(root, f), 'utf8').matchAll(/\bph-([a-z0-9]+(?:-[a-z0-9]+)*)/g)) used.add(m[1]);
used.delete('fill');

function glyphs(css, prefix) {
  const map = new Map();
  for (const m of css.matchAll(new RegExp(`\\.${prefix}\\.ph-([a-z0-9-]+):before\\s*{\\s*content:\\s*"\\\\([0-9a-f]+)"`, 'g'))) map.set(m[1], m[2]);
  return map;
}

const weights = [
  { name: 'regular', cls: 'ph', family: 'Phosphor', dir: 'regular', font: 'Phosphor.woff2' },
  { name: 'fill', cls: 'ph-fill', family: 'Phosphor-Fill', dir: 'fill', font: 'Phosphor-Fill.woff2' },
];

let out = `/* Generated by scripts/build-icons.mjs (npm run build:icons): Phosphor Icons 2.1.2, MIT. Do not edit. */\n`;
for (const w of weights) {
  const map = glyphs(readFileSync(join(pkg, w.dir, 'style.css'), 'utf8'), w.cls.replace('-', '\\-'));
  const names = [...used].filter((n) => map.has(n)).sort();
  const text = names.map((n) => String.fromCodePoint(parseInt(map.get(n), 16))).join('');
  const woff2 = await subsetFont(readFileSync(join(pkg, w.dir, w.font)), text, { targetFormat: 'woff2' });
  writeFileSync(join(root, `assets/fonts/phosphor-${w.name}.woff2`), woff2);
  const v = createHash('md5').update(woff2).digest('hex').slice(0, 8); // same as asset() in includes/design.php
  out += `@font-face{font-family:"${w.family}";src:url("../fonts/phosphor-${w.name}.woff2?v=${v}") format("woff2");font-weight:normal;font-style:normal;font-display:block}\n`;
  out += `.${w.cls}{font-family:"${w.family}"!important;speak:never;font-style:normal;font-weight:normal;font-variant:normal;text-transform:none;line-height:1;letter-spacing:0;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}\n`;
  out += names.map((n) => `.${w.cls}.ph-${n}:before{content:"\\${map.get(n)}"}`).join('\n') + '\n';
  console.log(`${w.name}: ${names.length} icons, ${woff2.length} bytes`);
}
writeFileSync(join(root, 'assets/css/icons.css'), out);
