<?php
// Insurance and assistance companies Acıbadem works with (contracted-institutions page, home page ticker)
return [
    'AA International Indonesia',
    'ABC Health Services',
    'ADAC',
    'AETNA',
    'AID Assistance',
    'AIG Travel Assist',
    'AP Companies',
    'AXA Global Healthcare',
    'AXA Partners',
    'Allianz Partners',
    'Allianz Worldwide Care',
    'April International Assistance',
    'Ardi Insurance',
    'Asia Medical Assistance',
    'Assist America',
    'Bupa Global',
    'Celta Assistance',
    'Cigna International',
    'Collinson Group',
    'Coris',
    'DHIG GmbH',
    'DKV — Deutsche Krankenversicherung',
    'DSW Zorgverzekeraar',
    'Daman National Health Insurance',
    'Direct Line',
    'Eexpedise Health',
    'Emergency Assistance Japan',
    'Euro-Center',
    'Eurocross',
    'Europ Assistance Global PPO',
    'Falck Global Assistance',
    'GMMI',
    'GeoBlue',
    'Global Benefits Georgia',
    'Global Excel',
    'Global Voyager Assistance (GVA)',
    'Globality Health',
    'HENNER',
    'HTH Worldwide',
    'Healix International',
    'Health 360°',
    'Healthwatch',
    'IMA — Inter Mutuelles Assistance',
    'IMS Istanbul Medical Services',
    'International Medical Group',
    'International SOS',
    'International SOS — Tricare',
    'Iris Global Solutions',
    'MCI — Medical Claims International',
    'MSH International',
    'Mapfre Assistance',
    'Marm Assistance',
    'Mayfair We Care',
    'Medicline',
    'Medlife Assistance',
    'Orion Assistance',
    'Planet Assist',
    'Prestige International UK',
    'QLM — Q Life & Medical Insurance',
    'Redstar',
    'Remed Assistance',
    'Retas Assistance',
    'SOS International',
    'United Healthcare',
    'VYV International',
    'Via Medica International',
    'WTP Medical Claims',
    'World Access (Blue Cross Blue Shield)',
    'World Health Organization (WHO)'
];
